2022-02-08 07:23:55,181 ERROR [C:\Users\afoc0\Work\Programming\Github\RadiationTherapyApplication\Rtapp\Rtapp\middleware.py:16] Reverse for 'toridog' not found. 'toridog' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\afoc0\anaconda3\envs\py37\lib\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'toridog' not found. 'toridog' is not a valid view function or pattern name.
